name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main   # đổi nếu bạn deploy từ branch khác

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_URL }}
      VITE_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}
      VITE_CLOUDINARY_UPLOAD_PRESET: ${{ secrets.VITE_CLOUDINARY_UPLOAD_PRESET }}
      VITE_CLOUDINARY_UPLOAD_FOLDER: ${{ secrets.VITE_CLOUDINARY_UPLOAD_FOLDER }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # hoặc version React bạn dùng

      - name: Install dependencies
        run: npm ci

      - name: Rebuild Tailwind Oxide
        run: npm rebuild @tailwindcss/oxide

      - name: Build React app
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
